### PR TITLE
Update tdi_pipeline_builder parameter string

### PR DESCRIPTION
**Pull request by 5abeel**
This CL updates all references to the parameter passed to the `tdi_pipeline_builder` program from `bf_pipeline_config_binary_file` to `tdi_pipeline_config_binary_file`. This change is part of the effort to update names removing the `bf_` legacy from codebase and naming convention

### CODE REVIEW

**Comment by ffoulkes** [comment]
I'd suggest adding a CL comment that explains the nature / purpose of the change, and seeing to it that the comment (or a variation thereof) goes into the commit itself.

The idea is to provide a rationale / summary of the changes made, for the benefit of (a) anyone who reviews the PR, and (b) anyone who does a `git log` after the PR is merged.

**Review by ffoulkes — APPROVED** [review]
LGTM

**Review by aashishkuma — APPROVED** [review]
LGTM.

**Review by nupuruttarwar — APPROVED** [review]
LGTM

**Pull request merged**
